# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://strudelinc.github.io
title: ShtrudelInc Site
email: #
author: Yuriy Ackermann && Pavel Zamyatin
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright &copy; 2017 StrudelInc. All Rights Reserved.'
credits: 'Credits: Yuriy Ackermann and Pavel Zamyatin. Photo by Negative Space <a href="https://www.pexels.com/u/negativespace/">pexels.com/u/negativespace</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/StrudelInc
  - title: github
    url: https://github.com/StrudelInc
  # - title: linkedin
  #   url:
